[package]
name = "forwarding_translation_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "macros",
    "io-util",
    "time",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
