[package]
name = "forwarding_translation_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "macros",
    "io-util",
    "time",
    "fs",
] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
packet_markers = { path = "packet_markers" }
toml = "0.9"
toml-example = "0.16"
